#  ==============  레포지토리 환경 변수  ==============
#   AWS_ROLE_ARN(워크스페이스 변수),  AWS_DEFAULT_REGION
#   AWS_ECR_REPO, AWS_ECR_NAME
#   AWS_TASK_DEFINITION, AWS_ECS_CLUSTER, AWS_ECS_SERVICE
# =================================================
#  내용
# =================================================
image: atlassian/default-image:2

pipelines:
  tags:
    "*.*.*":
      - step:
          name: Image Build and Push to ECR
          oidc: true
          services:
            - docker
          script:
            # Docker 이미지 빌드
            - docker build -t $AWS_ECR_NAME:$BITBUCKET_TAG -t $AWS_ECR_NAME .

            # ECR에 REPO 태그 지정
            - docker tag $AWS_ECR_NAME:$BITBUCKET_TAG $AWS_ECR_REPO/$AWS_ECR_NAME:$BITBUCKET_TAG
            - docker tag $AWS_ECR_NAME:$BITBUCKET_TAG $AWS_ECR_REPO/$AWS_ECR_NAME:latest

            # ECR에 푸시
            - pipe: atlassian/aws-ecr-push-image:2.6.0
              variables:
                AWS_OIDC_ROLE_ARN: $AWS_ROLE_ARN
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: $AWS_ECR_NAME # 실제 ECR 레포네임 사용.
                TAGS: "$BITBUCKET_TAG latest" # 이미지 태그_ 버전과 latest
